### ISSUE TITLE
error on running,

### ISSUE THREAD

**Issue by Mearafat** [initstring/cloud_enum#15] opened 2019-09-23 15:21 UTC
[!] Cannot access mutations file: /enum_tools/fuzz.txt

**Comment by initstring** [comment] 2019-09-24 04:34
Hi,

It looks like the tool is looking in "/" which is weird. Can you generate the error again, showing me the exact command you ran and the output of the following:

```
ls -al
pwd
```

Thanks!

**Comment by initstring** [comment] 2019-09-24 04:37
Also, just a hunch, try running the command like this from within the full directory:
```
./cloud_enum.py -k whatever
```

**Comment by amiralkizaru** [comment] 2019-09-27 11:54
@Mearafat 
Open ```cloud_enum.py```
search for ``` /enum_tools/fuzz.txt ``` and replace with ```enum_tools/fuzz.txt```
Make sure you ``` pip3 install -r requirement ```
```python3 cloud_enum.py -k company ````
Cheers

**Comment by initstring** [comment] 2019-09-27 20:24
Thanks @amiralkizaru. I see now what the issue is.

My testing was all done with running the script as `./cloud_enum.py`.

I've pushed a fix that is a bit more robust and should work no matter how the path is supplied.

I'm closing this ticket due to no reply from the @Mearafat - but please re-open if the issue persists.

Thanks!

```
-    script_path = os.path.dirname(__file__)
+    script_path = os.path.split(os.path.abspath(sys.argv[0]))[0]
```

**Closed** 2019-09-27 20:27 UTC

**Comment by Mearafat** [comment] 2019-09-30 08:32
I've solved the problem using this command, ./cloud_enum.py -k google
